# Generated by Django 2.1.15 on 2021-02-02 21:03

import django.contrib.postgres.fields.hstore
from django.db import migrations, models
from django.contrib.postgres.operations import HStoreExtension

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        HStoreExtension(),
        migrations.CreateModel(
            name='Dialogue',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('replies', django.contrib.postgres.fields.hstore.HStoreField()),
                ('dialogue_type', models.CharField(choices=[('SAMPLES', 'SAMPLES'), ('KEYWORDS', 'KEYWORDS')], max_length=20)),
                ('keywords', django.contrib.postgres.fields.hstore.HStoreField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fallback',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('replies', django.contrib.postgres.fields.hstore.HStoreField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Greeting',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('replies', django.contrib.postgres.fields.hstore.HStoreField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
