# Generated by Django 2.1.15 on 2021-02-03 16:58

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialogue',
            name='samples',
            field=django.contrib.postgres.fields.hstore.HStoreField(default={}),
        ),
        migrations.AlterField(
            model_name='dialogue',
            name='keywords',
            field=django.contrib.postgres.fields.hstore.HStoreField(default={}),
        ),
    ]
