# Generated by Django 2.1.15 on 2021-02-03 17:00

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_api', '0002_auto_20210203_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialogue',
            name='keywords',
            field=django.contrib.postgres.fields.hstore.HStoreField(default=dict),
        ),
        migrations.AlterField(
            model_name='dialogue',
            name='samples',
            field=django.contrib.postgres.fields.hstore.HStoreField(default=dict),
        ),
    ]
