# Generated by Django 2.1.15 on 2021-02-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_api', '0003_auto_20210203_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialogue',
            name='parent_id',
            field=models.CharField(default=str, max_length=100),
        ),
    ]
