# Generated by Django 2.1.15 on 2021-02-03 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_api', '0004_dialogue_parent_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('language', models.CharField(choices=[('en', 'en'), ('nb', 'nb')], max_length=20)),
                ('last_reply_id', models.CharField(default=None, max_length=100)),
            ],
        ),
    ]
