# Generated by Django 3.1.6 on 2021-02-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_api', '0005_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='language',
            field=models.CharField(choices=[('EN', 'en'), ('NB', 'nb')], max_length=20),
        ),
        migrations.AlterField(
            model_name='chat',
            name='last_reply_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dialogue',
            name='dialogue_type',
            field=models.CharField(choices=[('SAMPLES', 'samples'), ('KEYWORDS', 'keywords')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='chat',
            constraint=models.CheckConstraint(check=models.Q(language__in=['EN', 'NB']), name='bot_api_chat_language_valid'),
        ),
    ]
