# Generated by Django 3.1.6 on 2021-02-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_api', '0006_auto_20210203_1858'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='chat',
            name='bot_api_chat_language_valid',
        ),
        migrations.AlterField(
            model_name='chat',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('nb', 'Norwegian')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='chat',
            constraint=models.CheckConstraint(check=models.Q(language__in=['en', 'nb']), name='bot_api_chat_language_valid'),
        ),
    ]
