# Generated by Django 3.1.6 on 2021-02-03 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('language', models.CharField(choices=[('en', 'English'), ('nb', 'Norwegian')], max_length=20)),
                ('last_reply_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.CheckConstraint(check=models.Q(language__in=['en', 'nb']), name='conversation_conversation_language_valid'),
        ),
    ]
