# Generated by Django 3.1.6 on 2021-02-04 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='last_reply_id',
        ),
        migrations.AddField(
            model_name='conversation',
            name='message',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='conversation',
            name='reply_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
