# Generated by Django 3.1.6 on 2021-02-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0002_auto_20210204_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
