# Generated by Django 3.1.6 on 2021-02-05 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0003_auto_20210204_2057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='reply_id',
            new_name='last_reply_id',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='message',
        ),
    ]
