# Generated by Django 3.1.6 on 2021-02-03 20:04

import django.contrib.postgres.fields.hstore
from django.db import migrations, models
from django.contrib.postgres.operations import HStoreExtension

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        HStoreExtension(),
        migrations.CreateModel(
            name='Dialogue',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('replies', django.contrib.postgres.fields.hstore.HStoreField()),
                ('parent_id', models.CharField(default=str, max_length=100)),
                ('dialogue_type', models.CharField(choices=[('samples', 'Samples'), ('keywords', 'Keywords')], max_length=20)),
                ('keywords', django.contrib.postgres.fields.hstore.HStoreField(default=dict)),
                ('samples', django.contrib.postgres.fields.hstore.HStoreField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fallback',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('replies', django.contrib.postgres.fields.hstore.HStoreField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Greeting',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('replies', django.contrib.postgres.fields.hstore.HStoreField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
