# Generated by Django 3.1.6 on 2021-02-04 22:10

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialogue',
            name='replies',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.AlterField(
            model_name='fallback',
            name='replies',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.AlterField(
            model_name='greeting',
            name='replies',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
