# Generated by Django 3.1.6 on 2021-02-04 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210204_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialogue',
            name='replies',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='fallback',
            name='replies',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='greeting',
            name='replies',
            field=models.JSONField(),
        ),
    ]
