# Generated by Django 3.1.6 on 2021-02-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210204_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialogue',
            name='dialogue_type',
            field=models.CharField(choices=[('SAMPLES', 'Samples'), ('KEYWORDS', 'Keywords')], max_length=20),
        ),
    ]
