# Generated by Django 3.1.6 on 2021-02-05 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210205_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialogue',
            name='keywords',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='dialogue',
            name='samples',
            field=models.JSONField(default=dict),
        ),
    ]
